### ISSUE TITLE
cli usage

### ISSUE THREAD

**Issue by adelin-b** [pabra/json-literal-typer#4]
Allowing to use this package in scripts or in cli to make it easily usable.

```bash
json-literal-typer myType.json -o myTypeInterface.ts
```

**Comment by adelin-b** [comment]
Here is the gist that I wrote using yargs for my usecase of json-literal-typer

https://gist.github.com/adelin-b/9fd60900a71f111368cc31aea8907808

**Comment by pabra** [comment]
Thanks for caring.
CLI really still is a missing feature.
